---
name: Go Vulnerability detection

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch: # Manual workflow trigger

jobs:
  govulncheck:
    name: detect
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - name: Set up Go 1.18.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Govulncheck scan
        working-directory: ./src/github.com/${{ github.repository }}
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./... || true
